using ``def integer_validator(self, name, value):`` 
-------------------------------------------------

First import ``def integer_validator(self, name, value):``

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Now use it:

Function area():
    >>> bg = BaseGeometry()
    >>> bg.area()
    Traceback (most recent call last):
    ...
    Exception: area() is not implemented

Function integer_validator basic usage:
    >>> bg.integer_validator("holberton", 98)

Function integer_validator 0 input usage:
    >>> bg.integer_validator("holberton", 0)
    Traceback (most recent call last):
    ...
    ValueError: holberton must be greater than 0

Function integer_validator negative input usage:
    >>> bg.integer_validator("holberton", -1)
    Traceback (most recent call last):
    ...
    ValueError: holberton must be greater than 0

Function integer_validator non int input usage:
    >>> bg.integer_validator("holberton", "school")
    Traceback (most recent call last):
    ...
    TypeError: holberton must be an integer

Function integer_validator infinity input usage:
    >>> bg.integer_validator("holberton", float("inf"))
    Traceback (most recent call last):
    ...
    TypeError: holberton must be an integer

Function integer_validator large int input usage:
    >>> bg.integer_validator("holberton", 9999999999999999999999999)

Function integer_validator float input usage:
    >>> bg.integer_validator("holberton", 90.8)
    Traceback (most recent call last):
    ...
    TypeError: holberton must be an integer

Function integer_validator list usage:
    >>> bg.integer_validator("holberton", [90])
    Traceback (most recent call last):
    ...
    TypeError: holberton must be an integer

Function integer_validator list usage:
    >>> bg.integer_validator("holberton", (4,))
    Traceback (most recent call last):
    ...
    TypeError: holberton must be an integer

Function integer_validator list usage:
    >>> bg.integer_validator("holberton", {3, 4})
    Traceback (most recent call last):
    ...
    TypeError: holberton must be an integer

Function integer_validator list usage:
    >>> bg.integer_validator("holberton", True)
    Traceback (most recent call last):
    ...
    TypeError: holberton must be an integer

Function integer_validator list usage:
    >>> bg.integer_validator("holberton", None)
    Traceback (most recent call last):
    ...
    TypeError: holberton must be an integer

Function integer_validator no input usage:
    >>> bg.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'